### ISSUE TITLE
Error Error Fail to Scripts

### ISSUE THREAD

**Issue by DVSB** [rcschaff82/cwp_installers#1]
None of your scripts work, neither install nor uninstall, all files have to be removed by hand! You should really run it again here and start over. Posting that in the CWP forum is irresponsible to the user. These are the very things that make me cook. Responsibility also means ensuring that unfinished things are not let loose on the user, something that should be kept in mind at CWP. We test our scripts for almost a year to protect the user too!

**Comment by rcschaff82** [comment]
They worked fine 2 years ago when they were created.  If anything has changed in the core of CWP, I can't be held responsible for that.  As to install/uninstall, a more helpful comment would be the errors you receive.  But I welcome the feed back on something 2 years old, with no bug reports.
